name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install Autopep8
      run: pip install autopep8
    - name: Lint Action
      uses: wearerequired/lint-action@v2.3.0
      with:
        autopep8: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
